services:
  bark-server:
    profiles: ["bark"]
    image: finab/bark-server:latest
    container_name: bark-server
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT:-${COMPOSE_PROJECT_DIR}/data}/bark-server:/data
    networks:
      - homelab

networks:
  homelab:
    name: homelab
